// Implementation file for parser generated by fsyacc
module Parser
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "./language/Parser.fsy"


open Expression


# 12 "Parser.fs"
// This type is the type of tokens accepted by the parser
type token = 
  | EOF
  | INT of ( int32 )
  | LEFT_PARENTHES
  | RIGTH_PARENTHES
  | MINUS
  | PLUS
  | TIMES
  | DIVIDE
// This type is used to give symbolic names to token indexes, useful for error messages
type tokenId = 
    | TOKEN_EOF
    | TOKEN_INT
    | TOKEN_LEFT_PARENTHES
    | TOKEN_RIGTH_PARENTHES
    | TOKEN_MINUS
    | TOKEN_PLUS
    | TOKEN_TIMES
    | TOKEN_DIVIDE
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startstart
    | NONTERM_start
    | NONTERM_expression
    | NONTERM_expression1
    | NONTERM_expression2

// This function maps tokens to integer indexes
let tagOfToken (t:token) = 
  match t with
  | EOF  -> 0 
  | INT _ -> 1 
  | LEFT_PARENTHES  -> 2 
  | RIGTH_PARENTHES  -> 3 
  | MINUS  -> 4 
  | PLUS  -> 5 
  | TIMES  -> 6 
  | DIVIDE  -> 7 

// This function maps integer indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_EOF 
  | 1 -> TOKEN_INT 
  | 2 -> TOKEN_LEFT_PARENTHES 
  | 3 -> TOKEN_RIGTH_PARENTHES 
  | 4 -> TOKEN_MINUS 
  | 5 -> TOKEN_PLUS 
  | 6 -> TOKEN_TIMES 
  | 7 -> TOKEN_DIVIDE 
  | 10 -> TOKEN_end_of_input
  | 8 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startstart 
    | 1 -> NONTERM_start 
    | 2 -> NONTERM_expression 
    | 3 -> NONTERM_expression 
    | 4 -> NONTERM_expression 
    | 5 -> NONTERM_expression1 
    | 6 -> NONTERM_expression1 
    | 7 -> NONTERM_expression1 
    | 8 -> NONTERM_expression2 
    | 9 -> NONTERM_expression2 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 10 
let _fsyacc_tagOfErrorTerminal = 8

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | EOF  -> "EOF" 
  | INT _ -> "INT" 
  | LEFT_PARENTHES  -> "LEFT_PARENTHES" 
  | RIGTH_PARENTHES  -> "RIGTH_PARENTHES" 
  | MINUS  -> "MINUS" 
  | PLUS  -> "PLUS" 
  | TIMES  -> "TIMES" 
  | DIVIDE  -> "DIVIDE" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | EOF  -> (null : System.Object) 
  | INT _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | LEFT_PARENTHES  -> (null : System.Object) 
  | RIGTH_PARENTHES  -> (null : System.Object) 
  | MINUS  -> (null : System.Object) 
  | PLUS  -> (null : System.Object) 
  | TIMES  -> (null : System.Object) 
  | DIVIDE  -> (null : System.Object) 
let _fsyacc_gotos = [| 0us; 65535us; 1us; 65535us; 0us; 1us; 2us; 65535us; 0us; 2us; 16us; 4us; 4us; 65535us; 0us; 9us; 5us; 6us; 7us; 8us; 16us; 9us; 6us; 65535us; 0us; 14us; 5us; 14us; 7us; 14us; 10us; 11us; 12us; 13us; 16us; 14us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 3us; 6us; 11us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 3us; 1us; 2us; 3us; 1us; 1us; 3us; 2us; 3us; 9us; 1us; 2us; 3us; 2us; 5us; 6us; 1us; 3us; 3us; 3us; 5us; 6us; 3us; 4us; 5us; 6us; 1us; 5us; 1us; 5us; 1us; 6us; 1us; 6us; 1us; 7us; 1us; 8us; 1us; 9us; 1us; 9us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 8us; 10us; 14us; 16us; 20us; 22us; 26us; 30us; 32us; 34us; 36us; 38us; 40us; 42us; 44us; |]
let _fsyacc_action_rows = 18
let _fsyacc_actionTableElements = [|2us; 32768us; 1us; 15us; 2us; 16us; 0us; 49152us; 3us; 32768us; 0us; 3us; 4us; 5us; 5us; 7us; 0us; 16385us; 3us; 32768us; 3us; 17us; 4us; 5us; 5us; 7us; 2us; 32768us; 1us; 15us; 2us; 16us; 2us; 16386us; 6us; 10us; 7us; 12us; 2us; 32768us; 1us; 15us; 2us; 16us; 2us; 16387us; 6us; 10us; 7us; 12us; 2us; 16388us; 6us; 10us; 7us; 12us; 2us; 32768us; 1us; 15us; 2us; 16us; 0us; 16389us; 2us; 32768us; 1us; 15us; 2us; 16us; 0us; 16390us; 0us; 16391us; 0us; 16392us; 2us; 32768us; 1us; 15us; 2us; 16us; 0us; 16393us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 3us; 4us; 8us; 9us; 13us; 16us; 19us; 22us; 25us; 28us; 31us; 32us; 35us; 36us; 37us; 38us; 41us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 2us; 3us; 3us; 1us; 3us; 3us; 1us; 1us; 3us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 2us; 2us; 2us; 3us; 3us; 3us; 4us; 4us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 65535us; 16385us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 65535us; 16389us; 65535us; 16390us; 16391us; 16392us; 65535us; 16393us; |]
let _fsyacc_reductions ()  =    [| 
# 122 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  Expr )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startstart));
# 131 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 23 "./language/Parser.fsy"
                                             _1 
                   )
# 23 "./language/Parser.fsy"
                 :  Expr ));
# 142 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression1)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 26 "./language/Parser.fsy"
                                                                         Minus (_1, _3) 
                   )
# 26 "./language/Parser.fsy"
                 : 'expression));
# 154 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression1)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "./language/Parser.fsy"
                                                                         Plus (_1, _3) 
                   )
# 27 "./language/Parser.fsy"
                 : 'expression));
# 166 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression1)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 "./language/Parser.fsy"
                                                                         _1 
                   )
# 28 "./language/Parser.fsy"
                 : 'expression));
# 177 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression1)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression2)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 31 "./language/Parser.fsy"
                                                                         Times (_1, _3) 
                   )
# 31 "./language/Parser.fsy"
                 : 'expression1));
# 189 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression1)) in
            let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression2)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "./language/Parser.fsy"
                                                                         Divide (_1, _3) 
                   )
# 32 "./language/Parser.fsy"
                 : 'expression1));
# 201 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression2)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 33 "./language/Parser.fsy"
                                                                         _1 
                   )
# 33 "./language/Parser.fsy"
                 : 'expression1));
# 212 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data :  int32 )) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 36 "./language/Parser.fsy"
                                                                         Int _1 
                   )
# 36 "./language/Parser.fsy"
                 : 'expression2));
# 223 "Parser.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'expression)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "./language/Parser.fsy"
                                                                         Parentheses _2 
                   )
# 37 "./language/Parser.fsy"
                 : 'expression2));
|]
# 235 "Parser.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 11;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let start lexer lexbuf :  Expr  =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
